repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
  - repo: https://github.com/nicklockwood/SwiftFormat/
    rev: master
    hooks:
      - id: swiftformat
exclude: '.+\.generated\.swift' # exclude sourcery files